language: python
env: 
  global: 
  - secure: |-
      cTEIRPmfchu3EGqjXlIqBDxzo03NLU38WdWH6+D9ulFyWd4kys96jx7SJ9O3
      G9jaU2rkHAfzMSQbswBLcHh3LiduHx9FV8SIFa5X2kcUdoAh46WEzQH5qDLl
      dLtUqNmfC2uPloJkQaHkl2Sdi4EBO3VYch+ZlVH4UM4mi6P9hfw=
  - secure: |-
      edP4jb1H/w17C90SRwJWNv7wQwcwXJZcHMKqVSK9aWbuknb509YwAGdZtdsT
      aSlw1SgMW34HC0D3hOcTNn9AgICRKYlPy/utZl71B+PSe5uRDKyCO6Jg13ro
      t8VQNl/eUtQyuQ6b2CASzu5YhmLoWCOb70qevvyGGhIZ0Rbw9jw=
  - NOSE_WITH_COVERAGE=1
  - NOSE_COVER_PACKAGE=syra
  - NOSE_COVER_BRANCHES=1
  - NOSE_NOLOGCAPTURE=1
script: 
- nosetests
python: 
- "2.7"
install: 
- pip install .
